name: x_pr
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.5+15

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.6
  intl: 0.19.0
  flutter_riverpod: 2.5.1
  flutter_svg: 2.0.10+1
  flutter_secure_storage: 9.2.2
  talker_flutter: 4.2.3
  flutter_dotenv: 5.1.0
  shared_preferences: 2.2.3
  freezed_annotation: 2.4.1
  json_annotation: 4.9.0
  firebase_core: 3.3.0
  go_router: 14.1.4
  google_sign_in: 6.2.1
  dio: 5.4.3+1
  sign_in_with_apple: 6.1.0
  text_balancer: 0.1.5
  flutter_colorpicker: 1.1.0
  path_provider: 2.1.3
  cloud_firestore: 5.2.1
  uuid: 4.4.0
  share_plus: 9.0.0
  scroll_to_index: 3.0.1
  web_socket_channel: 3.0.0
  smooth_page_indicator: 1.2.0
  connectivity_plus: 6.0.3
  auto_size_text: 3.0.0
  package_info_plus: 8.0.0
  pinput: 5.0.0
  jwt_decoder: 2.0.1
  firebase_remote_config: 5.0.4
  url_launcher: 6.3.0
  google_generative_ai: 0.4.4
  device_preview: 1.2.0
  lottie: 3.1.2
  just_audio: 0.9.39
  firebase_crashlytics: 4.0.4
  wakelock_plus: 1.2.7
  store_redirect: 2.0.2
  ntp: 2.0.0
  audio_session: 0.1.21
  app_links: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0
  build_runner: 2.4.10
  freezed: 2.5.2
  json_serializable: 6.8.0
  flutter_flavorizr: 2.2.3
  flutter_launcher_icons: 0.13.1

flutter:
  uses-material-design: true
  assets:
    - lib/.env/dev/.env
    - lib/.env/prod/.env
    - assets/icons/
    - assets/logos/
    - assets/images/
    - assets/images/ko/
    - assets/images/en/
    - assets/lotties/
  fonts:
    - family: pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
    - family: blackHanSans
      fonts:
        - asset: assets/fonts/BlackHanSans-Regular.ttf
          weight: 400

flutter_intl:
  enabled: true
  arb_dir: lib/core/localization/l10n
  output_dir: lib/core/localization/generated
  main_locale: ko